<?php
$title = 'Edit album';
$this->headTitle($title);
?>
<h4><?php echo $this->escapeHtml($title); ?></h4>

<?php

$form = $this->form;
$id = $form->get('id')->getValue(); //Retorna valor do formulario, campo id
$form->setAttribute('id', 'formAlbumEdit');
$form->setAttribute('class', 'form-horizontal form-edit');
$form->setAttribute("action", "album/album/edit/" . "id/" . $id  . "/" . $this->escapeHtml($this->div));
$form->setAttribute('data-modulo', 'album');    //variavel de controle com o nome do modulo
$form->setAttribute('data-ctrl', 'album');      //variavel de controle com o nome do controle
$form->setAttribute('data-titulo', 'Album');         //variavel de controle com o titulo da tab
$form->setAttribute('data-div', $this->escapeHtml($this->div));         //variavel de controle com o titulo do nome da div abas

$form->prepare();

?>
<div class="container-fluid">
    <div class="col-md-12"></div>
    <?php echo $this->form()->openTag($form)  ?>
    <div class="form-group">
        <label for="title" class="col-sm-2 control-label">Title</label>
        <div class="col-md-6"><?php echo $this->formRow($form->get('title'), null, false);?></div>
        <div class="col-md-4"><?php echo $this->formHidden($form->get('id'))?></div>
      </div>
    <div class="form-group">
        <label for="artist" class="col-sm-2 control-label">Artist</label>
        <div class="col-md-6"><?php echo $this->formRow($form->get('artist'), null, false);?></div>
        <div class="col-md-4"></div>
    </div>
    <?php $form->get('genreid')->setAttribute('options', $this->options_sel('select id as id, genre as data from genre'),null,false); //Enviar Sempre como id e data para o helper?>
    <div class="form-group">
        <label for="genreid" class="col-sm-2 control-label">Genre</label>
        <div class="col-md-4"><?php echo $this->formRow($form->get('genreid'), null, false);?></div>
        <div class="col-md-6"></div>
    </div>
   <div class="form-group">
        <div class="col-md-1"><?php echo $this->formInput($form->get('submit'));?></div>
         <?php $form->get('voltar')->setAttribute('data-modo', 'voltar');  //variavel de controle modo:limpar/voltar?>
        <div class="col-md-1"><?php echo $this->formInput($form->get('voltar'));?></div>
        <div class="col-md-10"></div>
    </div>
    <?php echo $this->form()->closeTag($form) ?> 
</div>
