<div class="container-fluid painel"> 
    <div class="form-group">
      <label for="codigo" class="col-sm-2 control-label">Código:</label>
      <div class="col-sm-6">
          <?php echo $this->formRow($form->get('ncm_id'), null, false);?>
          <?php echo $this->formRow($form->get('codigo'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="ncm" class="col-sm-2 control-label">NCM:</label>
      <div class="col-sm-2">
          <?php echo $this->formRow($form->get('ncm'), null, false);?>
      </div>
       <label for="ex_tipi" class="col-sm-2 control-label">EX TIPI:</label>
      <div class="col-sm-2">
          <?php echo $this->formRow($form->get('ex_tipi'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="descricao" class="col-sm-2 control-label">Descrição:</label>
      <div class="col-sm-9">
          <?php echo $this->formRow($form->get('descricao'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="nat" class="col-sm-2 control-label">Cód Nat. Operação:</label>
      <div class="col-sm-2">
          <?php echo $this->formRow($form->get('nat'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="pis_entrada_id" class="col-sm-2 control-label">PIS de entrada:</label>
      <div class="col-sm-8">
         <?php $form->get('pis_entrada_id')->setAttribute('options', $this->options_sel("SELECT cst_pis_id as id, codigo||' - '||descricao as data FROM tab_cst_pis"),null,false); //Enviar Sempre como id e data para o helper?>
         <?php echo $this->formRow($form->get('pis_entrada_id'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="pis_saida_id" class="col-sm-2 control-label">PIS de saída:</label>
      <div class="col-sm-8">
         <?php $form->get('pis_saida_id')->setAttribute('options', $this->options_sel("SELECT cst_pis_id as id, codigo||' - '||descricao as data FROM tab_cst_pis"),null,false); //Enviar Sempre como id e data para o helper?>
         <?php echo $this->formRow($form->get('pis_saida_id'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="cofins_entrada_id" class="col-sm-2 control-label">COFINS de entrada:</label>
      <div class="col-sm-8">
         <?php $form->get('cofins_entrada_id')->setAttribute('options', $this->options_sel("SELECT cst_cofins_id as id, codigo||' - '||descricao as data FROM tab_cst_cofins"),null,false); //Enviar Sempre como id e data para o helper?>
         <?php echo $this->formRow($form->get('cofins_entrada_id'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="cofins_saida_id" class="col-sm-2 control-label">COFINS de saída:</label>
      <div class="col-sm-8">
         <?php $form->get('cofins_saida_id')->setAttribute('options', $this->options_sel("SELECT cst_cofins_id as id, codigo||' - '||descricao as data FROM tab_cst_cofins"),null,false); //Enviar Sempre como id e data para o helper?>
         <?php echo $this->formRow($form->get('cofins_saida_id'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="icms_pdv_id" class="col-sm-2 control-label">ICMS de saída PDV:</label>
      <div class="col-sm-8">
         <?php $form->get('icms_pdv_id')->setAttribute('options', $this->options_sel("SELECT icms_id as id, cst||' - '||descricao as data FROM cad_icms"),null,false); //Enviar Sempre como id e data para o helper?>
         <?php echo $this->formRow($form->get('icms_pdv_id'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="icms_nf_entrada_id" class="col-sm-2 control-label">ICMS de entrada NF:</label>
      <div class="col-sm-8">
         <?php $form->get('icms_nf_entrada_id')->setAttribute('options', $this->options_sel("SELECT icms_id as id, cst||' - '||descricao as data FROM cad_icms"),null,false); //Enviar Sempre como id e data para o helper?>
         <?php echo $this->formRow($form->get('icms_nf_entrada_id'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="icms_nf_saida_id" class="col-sm-2 control-label">ICMS de saída NF:</label>
      <div class="col-sm-8">
         <?php $form->get('icms_nf_saida_id')->setAttribute('options', $this->options_sel("SELECT icms_id as id, cst||' - '||descricao as data FROM cad_icms"),null,false); //Enviar Sempre como id e data para o helper?>
         <?php echo $this->formRow($form->get('icms_nf_saida_id'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="ipi_entrada_id" class="col-sm-2 control-label">IPI de entrada:</label>
      <div class="col-sm-8">
         <?php $form->get('ipi_entrada_id')->setAttribute('options', $this->options_sel("SELECT ipi_id as id, codigo||' - '||descricao as data FROM cad_ipi"),null,false); //Enviar Sempre como id e data para o helper?>
         <?php echo $this->formRow($form->get('ipi_entrada_id'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="ipi_saida_id" class="col-sm-2 control-label">IPI de saída:</label>
      <div class="col-sm-8">
         <?php $form->get('ipi_saida_id')->setAttribute('options', $this->options_sel("SELECT ipi_id as id, codigo||' - '||descricao as data FROM cad_ipi"),null,false); //Enviar Sempre como id e data para o helper?>
         <?php echo $this->formRow($form->get('ipi_saida_id'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="mva_st" class="col-sm-2 control-label">MVA:</label>
      <div class="col-sm-2">
          <?php echo $this->formRow($form->get('mva_st'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="cod_ncm" class="col-sm-2 control-label">CEST:</label>
      <div class="col-sm-2">
        <div class="input-group"> 
          <?php echo $this->formRow($form->get('cest_id'), null, false);?>
          <input id="cest" type="text" class="form-control input-sm"  placeholder="CEST">
          <div class="input-group-btn">
            <button class="btn btn-default btn-sm" type="button"><i class="glyphicon glyphicon-search"></i></button>
        </div>
        </div>
      </div>
      <div class="col-sm-6">
          <input id="desc_cest" type="text" class="form-control input-sm">
      </div>
    </div>
</div>
