<?php 
use Zend\Session\Container;
$sessao = new Container();

$url_order = 'ASC';
if ($this->order_by == 'ncm_id') {
    $url_order = ($this->order == 'ASC' ? 'DESC' : 'ASC');
} else if ($this->order_by == 'codigo') {
    $url_order = ($this->order == 'ASC' ? 'DESC' : 'ASC');
} else if ($this->order_by == 'ncm') {
    $url_order = ($this->order == 'ASC' ? 'DESC' : 'ASC');
}
?>

<table class="table table-condensed table-striped">
    <thead>
        <tr>
            <th><a href="#" onclick="returnView('cadimposto','cadncm',<?php echo $this->page ?>,'index','<?php echo 'dados_'.$this->escapeHtml($this->div); ?>','<?php echo $this->escapeHtml($this->search_frase); ?>','<?php echo $this->escapeHtml($this->data_ini); ?>','<?php echo $this->escapeHtml($this->data_fin); ?>',0,'NCM','ncm_id','<?php echo $url_order; ?>')" data-rel="<?php echo $this->escapeHtml($this->div);?>">Id <?php if ($this->order_by == 'ncm_id'): ?><i class="fa fa-sort-<?php echo $this->order == 'ASC' ? 'asc' : 'desc' ?>"></i><?php endif; ?></a></th>
            <th><a href="#" onclick="returnView('cadimposto','cadncm',<?php echo $this->page ?>,'index','<?php echo 'dados_'.$this->escapeHtml($this->div); ?>','<?php echo $this->escapeHtml($this->search_frase); ?>','<?php echo $this->escapeHtml($this->data_ini); ?>','<?php echo $this->escapeHtml($this->data_fin); ?>',0,'NCM','codigo','<?php echo $url_order; ?>')" data-rel="<?php echo $this->escapeHtml($this->div);?>">Código <?php if ($this->order_by == 'codigo'): ?><i class="fa fa-sort-<?php echo $this->order == 'ASC' ? 'asc' : 'desc' ?>"></i><?php endif; ?></a></th>
            <th><a href="#" onclick="returnView('cadimposto','cadncm',<?php echo $this->page ?>,'index','<?php echo 'dados_'.$this->escapeHtml($this->div); ?>','<?php echo $this->escapeHtml($this->search_frase); ?>','<?php echo $this->escapeHtml($this->data_ini); ?>','<?php echo $this->escapeHtml($this->data_fin); ?>',0,'NCM','ncm','<?php echo $url_order; ?>')" data-rel="<?php echo $this->escapeHtml($this->div);?>">NCM <?php if ($this->order_by == 'ncm'): ?><i class="fa fa-sort-<?php echo $this->order == 'ASC' ? 'asc' : 'desc' ?>"></i><?php endif; ?></a></th>
            <th><a href="#" data-rel="<?php echo $this->escapeHtml($this->div);?>">Data</a></th>
            <th>
            	<a href="#" onclick="returnView('cadimposto','cadncm',1,'add','<?php echo $this->escapeHtml($this->div); ?>','','','',0,'NCM')" data-rel="<?php echo $this->escapeHtml($this->div);?>">
                <?php 
                    if ($this->tipo_view  == false) {
                        echo "<i class=\"fa fa-plus-square\"></i>";
                    }
                ?>
                </a>
           	</th>
        </tr>
    </thead>
    <tbody> 
<?php foreach($this->dados as $dado) : ?>   
        <tr>
            
            <?php 
            if ($this->tipo_view  == true) {
                echo "<td><a data-id=\"".$this->escapeHtml($dado->ncm_id)."\" data-descricao=\"".$this->escapeHtml($dado->codigo)."\" data-ncm=\"".$this->escapeHtml($dado->ncm)."\" data-div=\"".$this->escapeHtml($this->div)."\"  class=\"ncm-atalho selecao\">".$this->escapeHtml($dado->ncm_id)."</a></td>";
            }else {
                echo "<td>".$this->escapeHtml($dado->ncm_id)."</td>";
            }
            
            ?>
            <td><?php echo $this->escapeHtml($dado->codigo);?></td>
            <td><?php echo $this->escapeHtml($dado->ncm);?></td>
            <td><?php echo $this->formata_data($this->escapeHtml($dado->data_cadastro));?></td>
            <td>
                <a href="#" onclick="returnView('cadimposto','cadncm',1,'edit','<?php echo $this->escapeHtml($this->div); ?>','','','','<?php echo $this->escapeHtml($dado->ncm_id);?>','NCM')" data-rel="<?php echo $this->escapeHtml($this->div);?>">
                	<?php 
                        if ($this->tipo_view  == false) {
                            echo "<i class=\"fa fa-pencil-square\"></i>";
                        }
                    ?> 
                </a>            
            </td>
        </tr>    
<?php endforeach; ?>
    </tbody>
</table>

<?php
if($this->dados instanceof Zend\Paginator\Paginator) {
    echo $this->paginationControl(
        $this->dados,
        'Sliding',
        'cadimposto/partials/paginator/paginator.phtml',
        array('div' => $this->div,
            'order_by' => $this->order_by,
            'order' => $this->order, 
            'page' => $this->page,
            'search_frase' => $this->search_frase,
            'data_ini' => $this->data_ini, 
            'data_fin' => $this->data_fin,
            'data_modulo' => 'cadimposto',
            'data_ctrl' => 'cadncm',
            'data_titulo' => 'NCM',
        )
    );
}
?> 