<div class="container-fluid painel"> 
    <div class="form-group">
      <label for="cod_ncm" class="col-sm-2 control-label">Classificação fiscal:</label>
      <div class="col-sm-2">
        <div class="input-group"> 
           <?php $form->get('ncm')->setValue($info['ncm']);?>
           <?php echo $this->formRow($form->get('ncm'), null, false);?>
           <?php echo $this->formRow($form->get('ncm_id'), null, false);?>
          <div class="input-group-btn">
            <button class="btn btn-default btn-sm atalhos" data-div="div_popup_produto" data-modulo="cadimposto" data-ctrl="cadncm" data-titulo="Produto" data-order_by="ncm_id" type="button">
            	<i class="glyphicon glyphicon-search"></i>
           </button>
        </div>
        </div>
      </div>
      <div class="col-sm-6">
          <?php $form->get('ncm_cod')->setValue($info['ncm_cod']);?>
          <?php echo $this->formRow($form->get('ncm_cod'), null, false);?>
      </div>
    </div>
    <div class="col-sm-12 dados-fiscais">
         <ul class="nav nav-tabs">
           <li class="active"><a data-toggle="tab" href="#menu_icms">Icms</a></li>
           <li><a data-toggle="tab" href="#menu_ipi">IPI</a></li>
           <li><a data-toggle="tab" href="#menu_pis">Pis</a></li>
           <li><a data-toggle="tab" href="#menu_cofins">Cofins</a></li>
         </ul>                        
         <div class="tab-content">
          <div id="menu_icms" class="tab-pane fade in active">
          <div class="container-fluid painel">
            <div class="form-group">
             <label for="icms_pdv_id" class="col-sm-2 control-label">Trib. ECF:</label>
              <div class="col-sm-6">
              	  <?php $form->get('icms_pdv_id')->setAttribute('options', $this->options_sel("SELECT icms_id as id, cst||' - '||descricao as data FROM cad_icms where uso in (4)"),null,false); //Enviar Sempre como id e data para o helper?>
                  <?php echo $this->formRow($form->get('icms_pdv_id'), null, false);?>
              </div>
            </div>
            <div class="form-group">
              <label for="cod_trib_pdv" class="col-sm-2 control-label">Cód. Tributação:</label>
              <div class="col-sm-2">
              		<?php $form->get('trib_pdv')->setValue($info['trib_pdv']);?>
                    <?php echo $this->formRow($form->get('trib_pdv'), null, false);?>
              </div>
              <label for="icms_pdv" class="col-sm-2 control-label">%Aliquota:</label>
              <div class="col-sm-2">
              		<?php $form->get('aliq_pdv')->setValue($info['aliq_pdv']);?>
                    <?php echo $this->formRow($form->get('aliq_pdv'), null, false);?>
              </div>
            </div>
            <div class="form-group">
             <label for="icms_nf_compra_id" class="col-sm-2 control-label">Icms de compra:</label>
              <div class="col-sm-6">
              	  <?php $form->get('icms_nf_entrada_id')->setAttribute('options', $this->options_sel("SELECT icms_id as id, cst||' - '||descricao as data FROM cad_icms where uso in (1,2)"),null,false); //Enviar Sempre como id e data para o helper?>
                  <?php echo $this->formRow($form->get('icms_nf_entrada_id'), null, false);?>
              </div>
            </div>
            <div class="form-group">
              <label for="base_icms_ent" class="col-sm-2 control-label">%Base:</label>
              <div class="col-sm-2">
              	  <?php $form->get('reducao_base_entrada')->setValue($info['reducao_base_entrada']);?>
                  <?php echo $this->formRow($form->get('reducao_base_entrada'), null, false);?>
              </div>
              <label for="aliq_icms_ent" class="col-sm-2 control-label">%Aliquota:</label>
              <div class="col-sm-2">
                 <?php $form->get('aliq_base_entrada')->setValue($info['aliq_base_entrada']);?>
                 <?php echo $this->formRow($form->get('aliq_base_entrada'), null, false);?>
              </div>
            </div>
            <div class="form-group">
              <label for="icms_nf_venda_id" class="col-sm-2 control-label">Icms de venda:</label>
              <div class="col-sm-6">
              	  <?php $form->get('icms_nf_saida_id')->setAttribute('options', $this->options_sel("SELECT icms_id as id, cst||' - '||descricao as data FROM cad_icms where uso in (1,3)"),null,false); //Enviar Sempre como id e data para o helper?>
                  <?php echo $this->formRow($form->get('icms_nf_saida_id'), null, false);?>
              </div>
            </div>
            <div class="form-group">
              <label for="base_icms_saida" class="col-sm-2 control-label">%Base:</label>
              <div class="col-sm-2">
                  <?php $form->get('reducao_base_saida')->setValue($info['reducao_base_saida']);?>
                  <?php echo $this->formRow($form->get('reducao_base_saida'), null, false);?>
              </div>
              <label for="aliq_icms_saida" class="col-sm-2 control-label">%Aliquota:</label>
              <div class="col-sm-2">
                  <?php $form->get('aliq_base_saida')->setValue($info['aliq_base_saida']);?>
                  <?php echo $this->formRow($form->get('aliq_base_saida'), null, false);?>
              </div>
            </div>
            <div class="form-group">
              <label for="mva_st" class="col-sm-2 control-label">MVA ST:</label>
              <div class="col-sm-2">
                  <?php echo $this->formRow($form->get('mva_st'), null, false);?>
              </div>
             
            </div>
          </div>
          </div>
          <div id="menu_ipi" class="tab-pane fade">
           <div class="container-fluid painel">
            <div class="form-group">
              <label for="ipi_compra_id" class="col-sm-2 control-label">IPI de compra:</label>
              <div class="col-sm-6">
                  <?php $form->get('ipi_entrada_id')->setAttribute('options', $this->options_sel("SELECT ipi_id as id, codigo||' - '||descricao as data FROM cad_ipi"),null,false); //Enviar Sempre como id e data para o helper?>
                  <?php echo $this->formRow($form->get('ipi_entrada_id'), null, false);?>
              </div>
            </div>                    
            <div class="form-group">
              <label for="aliq_ipi_ent" class="col-sm-2 control-label">%IPI:</label>
              <div class="col-sm-2">
                 <?php $form->get('aliq_ipi_entrada')->setValue($info['aliq_ipi_entrada']);?>
                  <?php echo $this->formRow($form->get('aliq_ipi_entrada'), null, false);?>
              </div>
              <label for="cst_pis_ent" class="col-sm-2 control-label">CST IPI:</label>
              <div class="col-sm-2">
                  <?php $form->get('cst_ipi_entrada')->setValue($info['cst_ipi_entrada']);?>
                  <?php echo $this->formRow($form->get('cst_ipi_entrada'), null, false);?>
              </div>
            </div> 
            <div class="form-group">
              <label for="pis_venda_id" class="col-sm-2 control-label">IPI de venda:</label>
              <div class="col-sm-6">
                  <?php $form->get('ipi_saida_id')->setAttribute('options', $this->options_sel("SELECT ipi_id as id, codigo||' - '||descricao as data FROM cad_ipi"),null,false); //Enviar Sempre como id e data para o helper?>
                  <?php echo $this->formRow($form->get('ipi_saida_id'), null, false);?>
              </div>
            </div>                    
            <div class="form-group">
              <label for="aliq_pis_ent" class="col-sm-2 control-label">%IPI:</label>
              <div class="col-sm-2">
                  <?php $form->get('aliq_ipi_saida')->setValue($info['aliq_ipi_saida']);?>
                  <?php echo $this->formRow($form->get('aliq_ipi_saida'), null, false);?>
              </div>
              <label for="cst_pis_ent" class="col-sm-2 control-label">CST IPI:</label>
              <div class="col-sm-2">
                  <?php $form->get('cst_ipi_saida')->setValue($info['cst_ipi_saida']);?>
                  <?php echo $this->formRow($form->get('cst_ipi_saida'), null, false);?>
              </div>
            </div> 
          </div>
    
          </div>
          <div id="menu_pis" class="tab-pane fade">
          <div class="container-fluid painel">
            <div class="form-group">
              <label for="pis_compra_id" class="col-sm-2 control-label">Pis de compra:</label>
              <div class="col-sm-6">
              	  <?php $form->get('pis_entrada_id')->setAttribute('options', $this->options_sel("SELECT cst_pis_id as id, codigo||' - '||descricao as data FROM tab_cst_pis"),null,false); //Enviar Sempre como id e data para o helper?>
                  <?php echo $this->formRow($form->get('pis_entrada_id'), null, false);?>
              </div>
            </div>                    
            <div class="form-group">
              <label for="aliq_pis_ent" class="col-sm-2 control-label">%Pis:</label>
              <div class="col-sm-2">
                  <?php $form->get('aliq_pis_entrada')->setValue($info['aliq_pis_entrada']);?>
                  <?php echo $this->formRow($form->get('aliq_pis_entrada'), null, false);?>
              </div>
              <label for="cst_pis_ent" class="col-sm-2 control-label">CST PIS:</label>
              <div class="col-sm-2">
                  <?php $form->get('cst_pis_entrada')->setValue($info['cst_pis_entrada']);?>
                  <?php echo $this->formRow($form->get('cst_pis_entrada'), null, false);?>
              </div>
            </div> 
            <div class="form-group">
              <label for="pis_venda_id" class="col-sm-2 control-label">Pis de venda:</label>
              <div class="col-sm-6">
                  <?php $form->get('pis_saida_id')->setAttribute('options', $this->options_sel("SELECT cst_pis_id as id, codigo||' - '||descricao as data FROM tab_cst_pis"),null,false); //Enviar Sempre como id e data para o helper?>
                  <?php echo $this->formRow($form->get('pis_saida_id'), null, false);?>
              </div>
            </div>                    
            <div class="form-group">
              <label for="aliq_pis_ent" class="col-sm-2 control-label">%Pis:</label>
              <div class="col-sm-2">
                  <?php $form->get('aliq_pis_saida')->setValue($info['aliq_pis_saida']);?>
                  <?php echo $this->formRow($form->get('aliq_pis_saida'), null, false);?>
              </div>
              <label for="cst_pis_ent" class="col-sm-2 control-label">CST PIS:</label>
              <div class="col-sm-2">
                  <?php $form->get('cst_pis_saida')->setValue($info['cst_pis_saida']);?>
                  <?php echo $this->formRow($form->get('cst_pis_saida'), null, false);?>
              </div>
            </div> 
          </div>
          </div>
          <div id="menu_cofins" class="tab-pane fade">
          <div class="container-fluid painel">
              <div class="form-group">
              <label for="cofins_compra_id" class="col-sm-2 control-label">Cofins de compra:</label>
              <div class="col-sm-6">
                  <?php $form->get('cofins_entrada_id')->setAttribute('options', $this->options_sel("SELECT cst_cofins_id as id, codigo||' - '||descricao as data FROM tab_cst_cofins"),null,false); //Enviar Sempre como id e data para o helper?>
                  <?php echo $this->formRow($form->get('cofins_entrada_id'), null, false);?>
              </div>
            </div>                    
            <div class="form-group">
              <label for="aliq_cofins_ent_id" class="col-sm-2 control-label">%Cofins:</label>
              <div class="col-sm-2">
                   <?php $form->get('aliq_cofins_entrada')->setValue($info['aliq_cofins_entrada']);?>
                   <?php echo $this->formRow($form->get('aliq_cofins_entrada'), null, false);?>
              </div>
              <label for="cst_cofins_ent" class="col-sm-2 control-label">CST COFINS:</label>
              <div class="col-sm-2">
                   <?php $form->get('cst_cofins_entrada')->setValue($info['cst_cofins_entrada']);?>
                   <?php echo $this->formRow($form->get('cst_cofins_entrada'), null, false);?>
              </div>
            </div> 
            <div class="form-group">
              <label for="cofins_venda_id" class="col-sm-2 control-label">Cofins de venda:</label>
              <div class="col-sm-6">
                  <?php $form->get('cofins_saida_id')->setAttribute('options', $this->options_sel("SELECT cst_cofins_id as id, codigo||' - '||descricao as data FROM tab_cst_cofins"),null,false); //Enviar Sempre como id e data para o helper?>
                  <?php echo $this->formRow($form->get('cofins_saida_id'), null, false);?>
              </div>
            </div>                    
            <div class="form-group">
              <label for="aliq_cofins_venda" class="col-sm-2 control-label">%Cofins:</label>
              <div class="col-sm-2">
                  <?php $form->get('aliq_cofins_saida')->setValue($info['aliq_cofins_saida']);?>
                  <?php echo $this->formRow($form->get('aliq_cofins_saida'), null, false);?>
              </div>
              <label for="cst_cofins_venda" class="col-sm-2 control-label">CST COFINS:</label>
              <div class="col-sm-2">
                  <?php $form->get('cst_cofins_saida')->setValue($info['cst_cofins_saida']);?>
                  <?php echo $this->formRow($form->get('cst_cofins_saida'), null, false);?>
              </div>
            </div> 
            </div>
            </div>
         </div>
     </div>
</div>
