<div class="container-fluid painel"> 
    <div class="form-group">
      <label for="descricao" class="col-sm-2 control-label">Descrição:</label>
      <div class="col-sm-6">
          <?php echo $this->formRow($form->get('descricao'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="cst" class="col-sm-2 control-label">CST:</label>
      <div class="col-sm-6">
          <?php echo $this->formRow($form->get('pis_id'), null, false);?>
          <?php $form->get('codigo')->setAttribute('options', $this->options_sel("SELECT codigo as id, codigo||' - '||descricao as data FROM tab_cst_pis"),null,false); //Enviar Sempre como id e data para o helper?>
          <?php echo $this->formRow($form->get('codigo'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="aliquota" class="col-sm-2 control-label">Aliquota:</label>
      <div class="col-sm-2">
         <?php echo $this->formRow($form->get('aliquota'), null, false);?>
      </div>
    </div>
</div>
