<table class="table table-condensed table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Código Ean</th>
            <th></th>
        </tr>
    </thead>
    <tbody> 
<?php foreach($this->dados as $dado) : ?>   
        <tr>
            <td><?php echo $this->escapeHtml($dado->sku_id);?></td>
            <td><?php echo $this->escapeHtml($dado->sku);?></td>
            <td>
                <a href="#" onclick="deletar(<?php echo $this->escapeHtml($dado->sku_id);?>)"><i class=" delete fa fa-times"></i>
                </a>
            </td>
        </tr>    
<?php endforeach; ?>
    </tbody>
</table>

<script type="text/javascript">
    function deletar(id){
        	var r = confirm("Deseja mesmo excluir esse registro?");
    	    if (r == true) {
   	    	 $.ajax({
	                url     :"album/album/delete/id/"+ id,// or the ure of your action
	                type    : 'POST',// POST, GET
	                cache   : false,
	                data    : {del: 'Yes'}, // the data from your form , in your case the :selected
	                dataType: "json",
	                success : function(data)
	                {
	                    alert(data.errorMessage);
	                    //Aqui se deve colocar uma rota para voltar ao index
	                    returnView('cadproduto','cadproduto',1,'index','<?php echo $this->escapeHtml($this->div);?>','','','','','Produto');
	                },
	    
	                error   : function(XMLHttpRequest, textStatus, errorThrown){
	                    alert('Error: ');
	                }
   	    	 });
    	    } else {
    	        txt = "You pressed Cancel!";
    	    }
    }
</script>