<?php
$title = 'Adicionar novo Fornecedor';
$this->headTitle($title);
?>
<h4><?php echo $this->escapeHtml($title); ?></h4>

<?php
$form = $this->form;
$id = "";
$form->setAttribute('id', 'formFornecedorAdd');
$form->setAttribute('class', 'form-horizontal form-add');
$form->setAttribute('action', 'cadparceiro/cadfornecedor/add');
$form->setAttribute('data-modulo', 'cadparceiro');    //variavel de controle com o nome do modulo
$form->setAttribute('data-ctrl', 'cadfornecedor');      //variavel de controle com o nome do controle
$form->setAttribute('data-titulo', 'Fornecedor');         //variavel de controle com o titulo da tab
$form->setAttribute('data-div', $this->escapeHtml($this->div));         //variavel de controle com o titulo do nome da div abas
$form->setAttribute('data-order_by', 'fornecedor_id');    //variavel de controle com o nome da chave primaria
$form->setAttribute('data-id', $id);    //variavel de controle com o id a ser consultado$form->prepare();
$form->prepare();
echo $this->form()->openTag($form);

?>
<div class="container-fluid">
	  <?php echo $this->form()->openTag($form)  ?>
          <div role="tabpanel">
            <ul class="nav nav-tabs" role="tablist">
              <li class="active"><a href="#abafornecedor1" data-toggle="tab" role="tab">Principal</a></li>
              <li><a href="#abafornecedor2" data-toggle="tab" role="tab"></a></li>
              <li><a href="#abfornecedor3" data-toggle="tab" role="tab"></a></li>
            </ul>
            <div id="tabContent1" class="tab-content">
              <div class="tab-pane fade in active cadastro" id="abafornecedor1">
                <?php echo $this->partial('cadparceiro/cadfornecedor/partialPrincipal.phtml', array('form' => $form, 'tipo' => 'add')); ?>
              </div>                
              <div class="tab-pane fade cadastro" id="abafornecedor2">
                
              </div>
              <div class="tab-pane fade cadastro" id="abafornecedor3">
                <p>Dropdown content#1</p>
              </div>
            </div>	     
          </div>
      <?php echo $this->partial('cadparceiro/partials/botoes/partialBotao.phtml', array('classe' => 'disabled')); ?>
      <?php echo $this->form()->closeTag($form) ?> 
      <div id="div_popup_fornecedor" class="popup"></div>
    </div>

