<?php
$title = 'Adicionar novo COFINS';
$this->headTitle($title);
?>
<h4><?php echo $this->escapeHtml($title); ?></h4>

<?php
$form = $this->form;
$form->setAttribute('id', 'formIcmsAdd');
$form->setAttribute('class', 'form-horizontal form-add');
$form->setAttribute('action', 'cadimposto/cadcofins/add');
$form->setAttribute('data-modulo', 'cadimposto');    //variavel de controle com o nome do modulo
$form->setAttribute('data-ctrl', 'cadcofins');      //variavel de controle com o nome do controle
$form->setAttribute('data-titulo', 'COFINS');         //variavel de controle com o titulo da tab
$form->setAttribute('data-div', $this->escapeHtml($this->div));         //variavel de controle com o titulo do nome da div abas
$form->prepare();
echo $this->form()->openTag($form);

?>
<div class="container-fluid">
	  <?php echo $this->form()->openTag($form)  ?>
          <div role="tabpanel">
            <ul class="nav nav-tabs" role="tablist">
              <li class="active"><a href="#abacofins1" data-toggle="tab" role="tab">Principal</a></li>
              <li><a href="#abacofins2" data-toggle="tab" role="tab"></a></li>
              <li><a href="#abacofins3" data-toggle="tab" role="tab"></a></li>
            </ul>
            <div id="tabContent1" class="tab-content">
              <div class="tab-pane fade in active cadastro" id="abacofins1">
                <?php echo $this->partial('cadcofins/partials/principal/partialPrincipal.phtml', array('form' => $form)); ?>
              </div>                
              <div class="tab-pane fade cadastro" id="abacofins2">
                
              </div>
              <div class="tab-pane fade cadastro" id="abacofins3">
                <p>Dropdown content#1</p>
              </div>
            </div>	     
          </div>
      <?php echo $this->partial('cadcofins/partials/botoes/partialBotao.phtml', array('classe' => 'disabled')); ?>
      <?php echo $this->form()->closeTag($form) ?> 
      <div id="div_popup_cofins" class="popup"></div>
    </div>

