<div class="row botoes">
    <div class="col-sm-2"></div>
    <div class="col-sm-1"><input class="btn btn-default btn-sm <?php echo $classe ?>" type="button" value="Novo"></div>
    <div class="col-sm-1"><input class="btn btn-default btn-sm" type="submit" value="Gravar"></div>
    <div class="col-sm-1"><button class="btn btn-default btn-sm <?php echo $classe ?>" type="button">Anterior</button></div>
    <div class="col-sm-1"><button class="btn btn-default btn-sm <?php echo $classe ?>" type="button">Próximo</button></div>
    <div class="col-sm-1"><input class="btn btn-default btn-sm" type="button" value="Voltar"></div>
    <div class="col-sm-1"><input class="btn btn-default btn-sm" type="button" value="Cancelar"></div>
</div>         
