<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sistema de Chamados</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-theme.min.css" rel="stylesheet">
    
    <!-- Jquery Ui Core CSS -->
    <link rel="stylesheet" href="jquery-ui/themes/humanity/jquery-ui.css">
    
    <!-- Easy Ui Core CSS -->
    
    <link href="themes/bootstrap/easyui.css" rel="stylesheet">
    <link href="themes/icon.css" rel="stylesheet">
    
    <!-- Custom CSS -->
    <link href="css/sb-admin.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
 
    <!-- Metis  Menu -->
    <link href="css/metisMenu.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    
    <link href="css/jquery.bootgrid.css" rel="stylesheet" />
    <script src="js/modernizr-2.8.1.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <div id="principal">
        <div id="wrapper" class="container-fluid">
    
            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html">SAC</a>
                </div>
         </nav>
    
        </div>
        
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-2">
                     <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                          <?php echo $this->partial('application/partial/partialMenuSideBar.phtml', array()); ?>
                    </div>
                    <!-- /.navbar-collapse -->
                </div>
                <div class="col-lg-10 conteudo"><?php echo $this->content; ?></div>
            </div>
            <!--<div class="row">
                <div class="text-center col-md-6 col-md-offset-3">
                    <p>Copyright &copy; 2015 &middot; All Rights Reserved &middot; <a href="#" >My Website</a></p>
                </div> 
            </div>   -->          
        </div>
        <!-- /.container-fluid -->
        <!-- jQuery -->
        <script src="js/jquery/jquery.min.js"></script>
    
        <!-- Bootstrap Core JavaScript -->
        <script src="js/bootstrap/bootstrap.min.js"></script>
 
        <!--Jquery Ui Core JavaScript -->        
        <script src="jquery-ui/jquery-ui.js"></script>
        
        <!-- Easy Ui Core JavaScript -->
        <script src="js/easyui/jquery.easyui.min.js"></script>
        
        <script src="js/assets/datepicker-pt-Br.js"></script>
        
        <!-- Funções Core JavaScript -->
        <script src="js/assets/functions.js"></script>
        
        <!-- Abas Core JavaScript -->
        <script src="js/assets/jquery.abas.js"></script>         
        
        <!-- Metis Menu JavaScript -->
        <script src="js/assets/metisMenu.js"></script>
       
    </div>
</body>

</html>
