<div class="row botoes">
    <div class="col-sm-2"></div>
    <div class="col-sm-1"><input class="btn btn-default btn-sm btn-novo <?php echo $classe ?>" type="button" value="Novo" data-modo="novo"></div>
    <div class="col-sm-1"><input class="btn btn-default btn-sm" type="submit" value="Gravar"></div>
    <div class="col-sm-1"><button class="btn btn-default btn-sm btn-prev <?php echo $classe ?>" type="button" data-modo="previous">Anterior</button></div>
    <div class="col-sm-1"><button class="btn btn-default btn-sm btn-next <?php echo $classe ?>" type="button" data-modo="next">Próximo</button></div>
    <div class="col-sm-1"><button class="btn btn-default btn-sm delete <?php echo $classe ?>" type="button" data-modo="next">Excluir</button></div>
    <div class="col-sm-1"><input class="btn btn-default btn-sm btn-voltar" type="button" value="Voltar" data-modo="voltar"></div>
    <div class="col-sm-1"><input class="btn btn-default btn-sm btn-limpar" type="button" value="Cancelar" data-modo="limparAdd"></div>
</div>         
