<div id='menu_icone' class="nav navbar-nav navbar-right">
	<!-- NOTIFICAÇÕES -->
	<div class='item_menu_icone'>
		<a id='lk_notificacoes' href="#"><i class='icomoon-untitled-110'></i></a>
		<span>2</span>
		<div id='box_notificacao'>{{
			View::make('Application.Layout.PartialButtons.botaoNotificacao') }}</div>
	</div>
	<!-- LOGOFF -->
	<div class='item_menu_icone'>
		<a id='lk_desliga' href="#"><i class='glyphicon glyphicon-off'></i></a>
	</div>
</div>