<ul id="menu" class="nav side-nav">    
    <li>
        <a href="javascript:;" ><i class="fa fa-fw fa-arrows-v"></i>Estoque<i class="fa fa-fw fa-caret-down"></i></a>
        <ul >
            <li>
                <a href="#"  data-rel="aba_produto" onclick="addTab('Produto','/cadproduto/cadproduto/index','aba_produto')">Produtos</a>
            </li>
            <li>
                <a href="#">Estoque</a>
            </li>
        </ul>
    </li>
    <li>
        <a href="javascript:;"><i class="fa fa-fw fa-arrows-v"></i> Impostos <i class="fa fa-fw fa-caret-down"></i></a>
        <ul >
            <li>
                 <a href="#"  data-rel="aba_ncm" onclick="addTab('NCM','/cadimposto/cadncm/index','aba_ncm')">NCM</a>
            </li>
            <li>
                <a href="#"  data-rel="aba_icms" onclick="addTab('ICMS','/cadimposto/cadicms/index','aba_icms')">ICMS</a>
            </li>
             <li>
                <a href="#"  data-rel="aba_ipi" onclick="addTab('IPI','/cadimposto/cadipi/index','aba_ipi')">IPI</a>
            </li>
            <li>
                <a href="#"  data-rel="aba_pis" onclick="addTab('PIS','/cadimposto/cadpis/index','aba_pis')">PIS</a>
            </li>
            <li>
                <a href="#"  data-rel="aba_cofins" onclick="addTab('COFINS','/cadimposto/cadcofins/index','aba_cofins')">COFINS</a>
            </li>
        </ul>
    </li>
    <li>
        <a href="javascript:;" ><i class="fa fa-fw fa-arrows-v"></i>Parceiros<i class="fa fa-fw fa-caret-down"></i></a>
        <ul >
            <li>
                <a href="#"  data-rel="aba_fornecedor" onclick="addTab('Fornecedor','/cadparceiro/cadfornecedor/index','aba_fornecedor')">Fornecedores</a>
            </li>
            <li>
                <a href="#">Clientes</a>
            </li>
            <li>
                <a href="#">Vendedores</a>
            </li>
            <li>
                <a href="#">Transportadoras</a>
            </li>
        </ul>
    </li>  
    <li>
        <a href="javascript:;" ><i class="fa fa-fw fa-arrows-v"></i>Departamentos<i class="fa fa-fw fa-caret-down"></i></a>
        <ul >
            <li>
                <a href="#" data-rel="aba_departamento" onclick="addTab('Seção','/caddepartamento/cadsecao/index','aba_departamento')">Seção</a>
            </li>
            <li>
                <a href="#" data-rel="aba_departamento" onclick="addTab('Grupo','/caddepartamento/cadgrupo/index','aba_departamento')">Grupo</a>
            </li>
            <li>
                <a href="#" data-rel="aba_departamento" onclick="addTab('Subgrupo','/caddepartamento/cadsubgrupo/index','aba_departamento')">Subgrupo</a>
            </li>
        </ul>
    </li>    
</ul>
