<ul id="menu" class="nav side-nav">    
    <li>
        <a href="javascript:;" ><i class="fa fa-fw fa-arrows-v"></i>Sac<i class="fa fa-fw fa-caret-down"></i></a>
        <ul >
            <li>
                <a href="#"  data-rel="aba_produto" onclick="addTab('Chamados','/sac/chamados/index','aba_chamados')">Chamados</a>
            </li>           
        </ul>
    </li>
    <li>
        <a href="javascript:;" ><i class="fa fa-fw fa-arrows-v"></i>Departamentos<i class="fa fa-fw fa-caret-down"></i></a>
        <ul >
            <li>
                <a href="#" data-rel="aba_departamento" onclick="addTab('Seção','/caddepartamento/cadsecao/index','aba_departamento')">Seção</a>
            </li>
            <li>
                <a href="#" data-rel="aba_departamento" onclick="addTab('Grupo','/caddepartamento/cadgrupo/index','aba_departamento')">Grupo</a>
            </li>
            <li>
                <a href="#" data-rel="aba_departamento" onclick="addTab('Subgrupo','/caddepartamento/cadsubgrupo/index','aba_departamento')">Subgrupo</a>
            </li>
        </ul>
    </li>    
</ul>
