<div class="container-fluid painel"> 
    <div class="form-group">
      <label for="codigo" class="col-sm-2 control-label">Código:</label>
      <div class="col-sm-2">
          <?php echo $this->formRow($form->get('secao_id'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="descricao" class="col-sm-2 control-label">Descrição:</label>
      <div class="col-sm-6">
          <?php echo $this->formRow($form->get('descricao'), null, false);?>
          <?php 
          if($tipo == 'edit') {
              $form->get('data_altera')->setAttribute('value', date("Y-m-d"));
              echo $this->formRow($form->get('data_altera'), null, false);
          }
          ?>
      </div>
    </div>
</div>
