<?php
$title = 'Delete album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete 
  '<?php echo $this->escapeHtml($albums->title); ?>' by 
  '<?php echo $this->escapeHtml($albums->artist); ?>'?
</p>
<?php 
$url = $this->url('album', array('action' => 'delete', 'id'=>$albums->id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$albums->id; ?>" />
  <input type="submit" name="del" value="Sim" />
  <input type="submit" name="del" value="Nao" />
</div>
</form>
