<div class="container-fluid painel"> 
    <div class="form-group">
      <label for="descricao" class="col-sm-2 control-label">Descrição:</label>
      <div class="col-sm-6">
          <?php echo $this->formRow($form->get('descricao'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="cst" class="col-sm-2 control-label">CST:</label>
      <div class="col-sm-6">
          <?php echo $this->formRow($form->get('icms_id'), null, false);?>
          <?php $form->get('cst')->setAttribute('options', $this->options_sel("SELECT codigo as id, codigo||' - '||descricao as data FROM tab_cst_icms"),null,false); //Enviar Sempre como id e data para o helper?>
          <?php echo $this->formRow($form->get('cst'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="descricao" class="col-sm-2 control-label">CSOSN:</label>
      <div class="col-sm-6">
          <?php $form->get('csosn')->setAttribute('options', $this->options_sel("SELECT codigo as id, codigo||' - '||descricao as data FROM tab_cst_icms"),null,false); //Enviar Sempre como id e data para o helper?>
          <?php echo $this->formRow($form->get('csosn'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="tributacao" class="col-sm-2 control-label">Cód de tributação:</label>
      <div class="col-sm-4">
          <?php echo $this->formRow($form->get('tributacao'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="origem" class="col-sm-2 control-label">Origem:</label>
      <div class="col-sm-4">
         <?php $form->get('origem')->setAttribute('options', $this->options_sel("SELECT codigo as id, codigo||' - '||descricao as data FROM tab_origem"),null,false); //Enviar Sempre como id e data para o helper?>
         <?php echo $this->formRow($form->get('origem'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="aliquota" class="col-sm-2 control-label">Aliquota:</label>
      <div class="col-sm-2">
         <?php echo $this->formRow($form->get('aliquota'), null, false);?>
      </div>
      <label for="base" class="col-sm-2 control-label">Base Redução:</label>
      <div class="col-sm-2">
         <?php echo $this->formRow($form->get('base'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="mod_icms" class="col-sm-2 control-label">Mod. Base Calc. ICMS:</label>
      <div class="col-sm-4">
         <?php echo $this->formRow($form->get('mod_icms'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="aliquota_st" class="col-sm-2 control-label">Alíquota de ST:</label>
      <div class="col-sm-2">
         <?php echo $this->formRow($form->get('aliquota_st'), null, false);?>
      </div>
      <label for="base_st" class="col-sm-2 control-label">Base de redução ST:</label>
      <div class="col-sm-2">
         <?php echo $this->formRow($form->get('base_st'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="mod_icms_st" class="col-sm-2 control-label">Mod. Base Calc. ICMS ST:</label>
      <div class="col-sm-4">
         <?php echo $this->formRow($form->get('mod_icms_st'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="uso" class="col-sm-2 control-label">Uso:</label>
      <div class="col-sm-4">
         <?php echo $this->formRow($form->get('uso'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="texto_nf_id" class="col-sm-2 control-label">ICMS de saída NF:</label>
      <div class="col-sm-8">
         <?php echo $this->formRow($form->get('texto_nf_id'), null, false);?>
      </div>
    </div>
    <div class="form-group">
      <label for="cod_tributacao_pdv" class="col-sm-2 control-label">Cód. tributação PDV:</label>
      <div class="col-sm-2">
         <?php echo $this->formRow($form->get('cod_tributacao_pdv'), null, false);?>
      </div>
      <label for="cfop" class="col-sm-2 control-label">CFOP:</label>
      <div class="col-sm-2">
         <?php echo $this->formRow($form->get('cfop'), null, false);?>
      </div>
    </div>
</div>
