<?php 
use Zend\Session\Container;
$sessao = new Container();

$url_order = 'ASC';
if ($this->order_by == 'id') {
    $url_order = ($this->order == 'ASC' ? 'DESC' : 'ASC');
} else if ($this->order_by == 'title') {
    $url_order = ($this->order == 'ASC' ? 'DESC' : 'ASC');
} else if ($this->order_by == 'artist') {
    $url_order = ($this->order == 'ASC' ? 'DESC' : 'ASC');
} else if ($this->order_by == 'genre') {
    $url_order = ($this->order == 'ASC' ? 'DESC' : 'ASC');
}
?>

<table class="table table-condensed table-striped">
    <thead>
        <tr>
            <th><a href="#" onclick="returnView('album','album',<?php echo $this->page ?>,'index','<?php echo 'dados_'.$this->escapeHtml($this->div); ?>','<?php echo $this->escapeHtml($this->search_frase); ?>','<?php echo $this->escapeHtml($this->data_ini); ?>','<?php echo $this->escapeHtml($this->data_fin); ?>',0,'Album','id','<?php echo $url_order; ?>')" data-rel="<?php echo $this->escapeHtml($this->div);?>">Id <?php if ($this->order_by == 'id'): ?><i class="fa fa-sort-<?php echo $this->order == 'ASC' ? 'asc' : 'desc' ?>"></i><?php endif; ?></a></th>
            <th><a href="#" onclick="returnView('album','album',<?php echo $this->page ?>,'index','<?php echo 'dados_'.$this->escapeHtml($this->div); ?>','<?php echo $this->escapeHtml($this->search_frase); ?>','<?php echo $this->escapeHtml($this->data_ini); ?>','<?php echo $this->escapeHtml($this->data_fin); ?>',0,'Album','title','<?php echo $url_order; ?>')" data-rel="<?php echo $this->escapeHtml($this->div);?>">Código <?php if ($this->order_by == 'title'): ?><i class="fa fa-sort-<?php echo $this->order == 'ASC' ? 'asc' : 'desc' ?>"></i><?php endif; ?></a></th>
            <th><a href="#" onclick="returnView('album','album',<?php echo $this->page ?>,'index','<?php echo 'dados_'.$this->escapeHtml($this->div); ?>','<?php echo $this->escapeHtml($this->search_frase); ?>','<?php echo $this->escapeHtml($this->data_ini); ?>','<?php echo $this->escapeHtml($this->data_fin); ?>',0,'Album','artist','<?php echo $url_order; ?>')" data-rel="<?php echo $this->escapeHtml($this->div);?>">Descrição <?php if ($this->order_by == 'artist'): ?><i class="fa fa-sort-<?php echo $this->order == 'ASC' ? 'asc' : 'desc' ?>"></i><?php endif; ?></a></th>
            <th><a href="#" onclick="returnView('album','album',<?php echo $this->page ?>,'index','<?php echo 'dados_'.$this->escapeHtml($this->div); ?>','<?php echo $this->escapeHtml($this->search_frase); ?>','<?php echo $this->escapeHtml($this->data_ini); ?>','<?php echo $this->escapeHtml($this->data_fin); ?>',0,'Album','genre','<?php echo $url_order; ?>')" data-rel="<?php echo $this->escapeHtml($this->div);?>">Alíquota <?php if ($this->order_by == 'genre'): ?><i class="fa fa-sort-<?php echo $this->order == 'ASC' ? 'asc' : 'desc' ?>"></i><?php endif; ?></a></th>
            <th><a href="#" data-rel="<?php echo $this->escapeHtml($this->div);?>">Data</a></th>
            <th><a href="#" onclick="returnView('cadimposto','cadipi',1,'add','<?php echo $this->escapeHtml($this->div); ?>','','','',0,'IPI')" data-rel="<?php echo $this->escapeHtml($this->div);?>">
                <i class="fa fa-plus-square"></i></a></th>
        </tr>
    </thead>
    <tbody> 
<?php foreach($this->dados as $dado) : ?>   
        <tr>
            <td><?php echo $this->escapeHtml($dado->ipi_id);?></td>
            <td><?php echo $this->escapeHtml($dado->codigo);?></td>
            <td><?php echo $this->escapeHtml($dado->descricao);?></td>
            <td><?php echo $this->escapeHtml($dado->aliquota);?></td>
            <td><?php echo $this->formata_data($this->escapeHtml($dado->data_cadastro));?></td>
            <td>
                <a href="#" onclick="returnView('album','album',1,'edit','<?php echo $this->escapeHtml($this->div); ?>','','','','<?php echo $this->escapeHtml($dado->ipi_id);?>','Album')" data-rel="<?php echo $this->escapeHtml($this->div);?>">
                <i class="fa fa-pencil-square"></i>                
                </a>&nbsp;
                <a href="#" onclick="deletar(<?php echo $this->escapeHtml($dado->ipi_id);?>)"><i class=" delete fa fa-times"></i>
                </a>
            </td>
        </tr>    
<?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">
    function deletar(id){
        	var r = confirm("Deseja mesmo excluir esse registro?");
    	    if (r == true) {
   	    	 $.ajax({
	                url     :"album/album/delete/id/"+ id,// or the ure of your action
	                type    : 'POST',// POST, GET
	                cache   : false,
	                data    : {del: 'Yes'}, // the data from your form , in your case the :selected
	                dataType: "json",
	                success : function(data)
	                {
	                    alert(data.errorMessage);
	                    //Aqui se deve colocar uma rota para voltar ao index
	                    returnView('album','album',1,'index','<?php echo $this->escapeHtml($this->div);?>','','','','','Album');
	                },
	    
	                error   : function(XMLHttpRequest, textStatus, errorThrown){
	                    alert('Error: ');
	                }
   	    	 });
    	    } else {
    	        txt = "You pressed Cancel!";
    	    }
    }
</script>
<?php
if($this->dados instanceof Zend\Paginator\Paginator) {
    echo $this->paginationControl(
        $this->dados,
        'Sliding',
        'cadipi/partials/paginator/paginator.phtml',
        array('div' => $this->div,
            'order_by' => $this->order_by,
            'order' => $this->order, 
            'page' => $this->page,
            'search_frase' => $this->search_frase,
            'data_ini' => $this->data_ini, 
            'data_fin' => $this->data_fin
        )
        );
}
?> 