<?php
$title = 'Adicionar novo IPI';
$this->headTitle($title);
?>
<h4><?php echo $this->escapeHtml($title); ?></h4>

<?php
$form = $this->form;
$id = '';
$form->setAttribute('id', 'formIpiAdd');
$form->setAttribute('class', 'form-horizontal form-add');
$form->setAttribute('action', 'cadimposto/cadipi/add');
$form->setAttribute('data-modulo', 'cadimposto');    //variavel de controle com o nome do modulo
$form->setAttribute('data-ctrl', 'cadipi');      //variavel de controle com o nome do controle
$form->setAttribute('data-titulo', 'IPI');         //variavel de controle com o titulo da tab
$form->setAttribute('data-div', $this->escapeHtml($this->div));         //variavel de controle com o titulo do nome da div abas
$form->setAttribute('data-order_by', 'ipi_id');    //variavel de controle com o nome da chave primaria
$form->setAttribute('data-id', $id);    //variavel de controle com o id a ser consultado
$form->prepare();

?>
<div class="container-fluid">
	  <?php echo $this->form()->openTag($form)  ?>
          <div role="tabpanel">
            <ul class="nav nav-tabs" role="tablist">
              <li class="active"><a href="#abaipi1" data-toggle="tab" role="tab">Principal</a></li>
              <li><a href="#abaipi2" data-toggle="tab" role="tab"></a></li>
              <li><a href="#abipi3" data-toggle="tab" role="tab"></a></li>
            </ul>
            <div id="tabContent1" class="tab-content">
              <div class="tab-pane fade in active cadastro" id="abaipi1">
                <?php echo $this->partial('partialPrincipal.phtml', array('form' => $form, 'tipo' => 'edit')); ?>
              </div>                
              <div class="tab-pane fade cadastro" id="abaipi2">
                
              </div>
              <div class="tab-pane fade cadastro" id="abaipi3">
                <p>Dropdown content#1</p>
              </div>
            </div>	     
          </div>
      <?php echo $this->partial('cadimposto/partials/botoes/partialBotao.phtml', array('classe' => 'disabled')); ?>
      <?php echo $this->form()->closeTag($form) ?> 
      <div id="div_popup_ipi" class="popup"></div>
    </div>

